site_name: Polly Documentation
nav:
  - Home: index.md
  - Getting Started:
    - Polly CLI: Getting Started/Polly CLI.md
    - Projects: Getting Started/Project Management Dashboard.md
  - Apps:
      - Introduction: Apps/Introduction.md
      - Notebooks: Apps/Polly Notebooks.md
      - Metabolomics Data:
        - Dual Mode: Apps/Metabolomic Data/Introduction.md
        - Labeled LC-MS Workflow: Apps/Metabolomic Data/Introduction.md
        - Labeled LC-MS/MS Workfow: Apps/Metabolomic Data/Introduction.md
        - MetScape: Apps/Metabolomic Data/Introduction.md
        - El-MAVEN Phi Realtive LC-MS: Apps/Metabolomic Data/Introduction.md
        - FirstView: Apps/Metabolomic Data/Introduction.md
        - Untargeted Pipeline: Apps/Metabolomic Data/Introduction.md
        - QuantFit: Apps/Metabolomic Data/Introduction.md
        - CD-QuantFit: Apps/Metabolomic Data/Introduction.md
      - Screening and Sequencing Data: 
        - CRISPR: Apps/Screening & Sequencing Data/CRISPR Screening.md
        - High Throughput Drug Screening: Apps/Screening & Sequencing Data/High Throughput Drug Screening.md
        - RNA Seq Qorkflow: Apps/Screening & Sequencing Data/RNA Seq Workflow.md
      - Proteomics Data:
        - Protoemics Workflow: Apps/Proteomics Data/Proteomcis Workflow.md
      - Lipidomics Data:
        - Lipidomics Visualization Dashboard: Apps/Lipidomics Data/Lipidomics Visualziation Dashboard.md
      - Multi-omics Data:
        - IntOmix: Apps/Multi-omic Data/IntOmix.md
  - Data Lake: Data Lake.md
theme: readthedocs
site_favicon: img/elucidata.ico